version: '3'
services:
  drone:
    restart: always
    build:
      context: .
    volumes:
      - ${PWD}/data:/opt/drone/data
      - ${PWD}/config.yaml:/opt/drone/config.yaml:ro

  rod:
    restart: always
    image: ghcr.io/go-rod/rod:v0.116.1

  carbon:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile.carbon
