services:
  drone:
    restart: always
    depends_on:
      - rod
      - carbon
      - rayso
      - javahighlight
    build:
      context: .
    volumes:
      - ./data:/opt/drone/data
      - ./config.yaml:/opt/drone/config.yaml:ro

  rod:
    restart: always
    image: ghcr.io/go-rod/rod:v0.116.1
    volumes:
      - ./data:/opt/drone/data

  carbon:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile.carbon

  rayso:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile.rayso

  javahighlight:
    restart: always
    build:
      context: ./third-party/javahightlight
      dockerfile: Dockerfile
