services:
  rod:
    restart: always
    image: ghcr.io/go-rod/rod:v0.116.1
    ports:
      - '7317:7317'
      - '56174:56174'
    volumes:
      - ${PWD}/data:/opt/drone/data

  carbon:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile.carbon
    ports:
      - '3000:3000'

  rayso:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile.rayso
    ports:
      - '3001:3001'

  javahighlight:
    restart: always
    build:
      context: ./third-party/javahightlight
      dockerfile: Dockerfile
    ports:
      - '3002:3002'
