version: '3'
services:
  drone:
    restart: always
    build:
      context: .
    volumes:
      - data:/opt/drone/data
    env_file: .env
    environment:
      - DRONE_TG_BOT_API_KEY=${DRONE_TG_BOT_API_KEY}
      - DRONE_LC_DAILY_CRON=${DRONE_LC_DAILY_CRON}
      - DRONE_NC_DAILY_CRON=${DRONE_NC_DAILY_CRON}
      - DRONE_BOAR_D_WHITE_CHAT_ID=${DRONE_BOAR_D_WHITE_CHAT_ID}
      - DRONE_BOAR_D_WHITE_LEET_CODE_THREAD_ID=${DRONE_BOAR_D_WHITE_LEET_CODE_THREAD_ID}
      - DRONE_NC_DAILY_START_DATE=${DRONE_NC_DAILY_START_DATE}
      - DRONE_DAILY_STICKER_IDS=${DRONE_DAILY_STICKER_IDS}
      - DRONE_DP_STICKER_ID=${DRONE_DP_STICKER_ID}
      - DRONE_TG_LONG_POLLER_TIMEOUT=${DRONE_TG_LONG_POLLER_TIMEOUT}
      - DRONE_MOCK_EGOR_ENABLED=${DRONE_MOCK_EGOR_ENABLED}
      - DRONE_MOCK_EGOR_PERIOD=${DRONE_MOCK_EGOR_PERIOD}
      - DRONE_MOCK_EGOR_STICKER_ID=${DRONE_MOCK_EGOR_STICKER_ID}

volumes:
  data:
