version: '3'
services:
  drone:
    restart: always
    build:
      context: .
    volumes:
      - data:/opt/drone/data
      - ${PWD}/config.yaml:/opt/drone/config.yaml
    env_file: .env

volumes:
  data:
