FROM node:18.20.4-alpine3.19 AS builder

WORKDIR /opt/rayso

RUN apk add --update git \
    && rm -rf /var/cache/apk/* \
    && git clone https://github.com/raycast/ray-so.git . \
    && git reset --hard eb303710b39b407c5400b05837a3eb91bd1ec074 \
    && npm install \
    && npm run build \
    && npm prune --production


FROM node:18.20.4-alpine3.19

WORKDIR /opt/rayso

COPY --from=builder /opt/rayso /opt/rayso

CMD ["yarn", "start", "-p", "3001"]
