badger_path: "data/badger"
features:
  snippets_generation_enabled: false
tg:
  api_key: ""
  long_poller_timeout: "10s"
  admin_chat_id: 230400818
rod:
  host: "rod" # inside docker, for local use "docker run --rm -p 7317:7317 ghcr.io/go-rod/rod:v0.116.1" and 127.0.0.1 as host
  port: 7317
  downloads_folder: "/opt/drone/data/rod/downloads"
media_generator:
  carbon_url: "http://carbon:3000"
  rayso_url: "http://rayso:3001"
  javahighlight_url: "http://javahighlight:3002"
  use_carbon: false
  use_rayso: false
  use_javahighlight: true
  rod_downloads_folder: "/opt/drone/data/rod/downloads"
boardwhite:
  chat_id: -1001640461540
  leetcode_thread_id: 10095
  leetcode_chickens_thread_id: 372377
  flood_thread_id: 11214
  interviews_thread_id: 10100
leetcode:
  session: ""
  csrf: ""
leetcode_daily:
  cron: "5 0 * * *" # every day at 00:05 UTC
  rating_cron: "0 6 1 * *" # every month at 06:00 UTC
neetcode_daily:
  cron: "0 12 * * *" #  every day at 12:00 UTC
  rating_cron: "1 6 1 * *" # every month at 06:01 UTC
daily_sticker_ids:
  - "CAACAgIAAxkBAAELpiFl7G4Rn8WQBK3AaDiAMn6ixTUR7gACzzkAAr-TAAFK91qMnVpp9TQ0BA"
  - "CAACAgIAAxkBAAELqk5l72yJkbx4_vskG3n6zWoWaAnA3QACazYAArJX2UsY5inoNwaFoTQE"
  - "CAACAgIAAxkBAAELsFZl8hFWX-2VvyppubPYPnLFrVeLPgACZjEAAmSSoUrAsMs8kC1omDQE"
  - "CAACAgIAAxkBAAELsFRl8hE8RstoYI8E3RfKk2N1LRX-qQAC4TUAAhJs2ElFZyKM69wJfDQE"
  - "CAACAgIAAxkBAAELsFJl8hEuJlU_1RK4nbpq3_iuZYsAATAAAi01AALtZihJuuf3iNlNcbU0BA"
  - "CAACAgIAAxkBAAELsFBl8hEnQ9Ie_ANBN_TfzbDjvMck2wACVToAAhqdoEiRsQbJLo-jijQE"
  - "CAACAgIAAxkBAAELsE5l8hEfhr-0Dn7BfsI9sDWA3I0t0wACSzUAAtS3aUj_OJb99K6DkjQE"
  - "CAACAgIAAxkBAAELsExl8hEZTP0DFsf6hUDiZnx-i9I25wACpTEAAlp3YUhJNRORPRx_5DQE"
  - "CAACAgIAAxkBAAELsEpl8hERg5mpamVfTo_SCgZRatbi6wACCzcAAqVsKEjLAvd1EuqdLzQE"
  - "CAACAgIAAxkBAAELsEhl8hENAzygO8iFauBYZD0XPYqD3gACkTQAArnoCUjvaNgUd-BoHDQE"
  - "CAACAgIAAxkBAAELsEZl8hD-i6wYaeLUMtP8MWhZwZoy3gACAjMAAs0gAUjsT0apWa4cRTQE"
  - "CAACAgIAAxkBAAELsERl8hD1xsuLUYRD9F4a8ekVAgg8VAACgDgAAsuH-UvwActGs5DfMzQE"
  - "CAACAgIAAxkBAAELsEJl8hDUc-b0jyDfeH6Ct2McMp4mlAACOzcAAquEmUsMP7ObsCcumTQE"
  - "CAACAgIAAxkBAAEMTOJmapw65q2fQiOQ-q3_B6RV9_7qagACNAADBcpWCO24fpev5IapNQQ"
  - "CAACAgIAAxkBAAEMTORmapw_xM94EVu2j6zINAlSYbcsogACTAADBcpWCJEC-PYX7CmtNQQ"
  - "CAACAgIAAxkBAAEMTOZmapxMTnRwYwmwsUaEsDw70HbfJwACEAADBcpWCOqNywPZHSK1NQQ"
  - "CAACAgIAAxkBAAEMTOhmapxcGWbkHGnKsEj_XLSOC8FtJgACwRYAAmLD-EldkLhdqjpVMDUE"
  - "CAACAgIAAxkBAAEMTOxmapxstQLBnvTk3zzEHJ-cHLiBdgACkh4AAqhMIUh2wIwKN77UfzUE"
  - "CAACAgIAAxkBAAEMTO5mapx14v9sDaCBqbMbjOCuaTmj-wACAx4AAlOqQErr0hfP2b25hzUE"
  - "CAACAgEAAxkBAAEMTPJmapyrwuh-bHr1DANmoRaiD7_XwQAC7xIAApl_iAJsyiP2eI4MKDUE"
  - "CAACAgEAAxkBAAEMTPRmapy22Zjj6OV0aAwVJoLgpo3YTAACoQ8AApl_iAIczmqdOf8MDTUE"
  - "CAACAgEAAxkBAAEMTPZmapy8EMeLka9fZlAHOJqcPcYB8gACow8AApl_iALey-njdminmjUE"
  - "CAACAgIAAxkBAAEMTPhmapzuIaxJjpwwvHJAtAL4a_0Q6gACUgoAAtA90gixaS0UHuYwgjUE"
  - "CAACAgIAAxkBAAEMTPpmap46qgL2bAOFrTCmm_qlNevK8gACMk0AAjtToEqXoqlSuH4pwTUE"
  - "CAACAgIAAxkBAAEMTPxmaqA3xQs2VIIsvRe_Zz8b8f_YfgACDgADWQxTEp_ypEYr7NfVNQQ"
  - "CAACAgIAAxkBAAEMTP5maqA87gNxFLfOIVnVKQb9p87FwAACAQADWQxTEoGwOR2Ph1igNQQ"
  - "CAACAgIAAxkBAAEMTQABZmqgV7BhQEcw5KIbsNts8sHOJgYAAikAA1kMUxKOy898mJBVazUE"
  - "CAACAgIAAxkBAAEMTQJmaqB9_d9Ciu3HY3KXTrTa-QljMwACLgADWQxTEhJbEPYsQmF0NQQ"
  - "CAACAgIAAxkBAAEMyytm4duvt5_FNyuhO08zZaK9u5kCuwACaEEAAj0W-EufbYl3CYVEhDYE"
  - "CAACAgEAAxkBAAEMyyxm4duvzlohOfq1ejeclNPyU7E6swACxAIAAsiCWUaaBTEPi30r4TYE"
  - "CAACAgIAAxkBAAEMyzFm4dwNGYUc-b2XiguHedbw_2WeBgACDU0AAoM7iUqU54QUZX89XTYE"
  - "CAACAgIAAxkBAAEMyzJm4dwNxYOBTtvhmDJhxfDLYDGFzgAC3BQAApFJyUsZSvKXHDxpbjYE"
  - "CAACAgIAAxkBAAEMyzNm4dwNwJ3eaiioJCxxrJWy0h1S9gACCQADWQxTEneyD59JaW0_NgQ"
  - "CAACAgIAAxkBAAEMyzRm4dwNGYLUTEhQV3TbqRPodfIQQQACUwoAAtA90ghMw1A3TdNNzDYE"
  - "CAACAgIAAxkBAAEMyzVm4dwN2kXCZi4ZTzEUXjLQe79y2QACGAEAAve-rAL5W8IILMzxmDYE"
  - "CAACAgIAAxkBAAEMyzZm4dwNkTFBqoYpXUp8YD1DI2_QLQAC6gIAAkGRHwE3-kAvpuo4TjYE"
  - "CAACAgEAAxkBAAEMyzdm4dwNHqROdEOi571tVFO-eEUL_gACoQ8AApl_iAIczmqdOf8MDTYE"
  - "CAACAgIAAxkBAAEMyzhm4dwNRrvp_qFINW49nKGJLoTFEgACjiEAAqT1qUuUDW4bm3gFXDYE"
  - "CAACAgEAAxkBAAEMyzlm4dwN6pjsoXxSrKC3m0Ip3kMoxQACLwMAAj1jrQcH028zNnTQGzYE"
  - "CAACAgIAAxkBAAEMyzpm4dwNKnzSi0kM7tjVnD96BLABKwACvEMAApEjCEv0-Zi9awyLozYE"
  - "CAACAgIAAxkBAAEMyztm4dwN9eT0MpwF9PzJRM5GuPEhkwACUAYAAtCG-woJ2NSmqzz6NzYE"
  - "CAACAgIAAxkBAAEMyzxm4dwNdsRwxDT5IbHTpwZWFNAoqQAC2gUAAiMFDQABgxgF6ASMVw02BA"
  - "CAACAgIAAxkBAAEMyz1m4dwN6wEdUSER-hrugQiojdByGwACg58BAAFji0YMFqivT1cZsl82BA"
  - "CAACAgQAAxkBAAEMyz5m4dwN1j2epw2ty48GF0elYTBxXAACehAAAr-4OVGj_HvF-s_vizYE"
  - "CAACAgIAAxkBAAEMyz9m4dwND2rbB_fzrmUb-jdPE79hyQACkwADqq5SBFq_aAsSh0pHNgQ"
  - "CAACAgIAAxkBAAEMy0Bm4dwNyV_5j38QstvKt-szQkLMcQACjUoAAkOmYErWmobZEO-qdjYE"
  - "CAACAgIAAxkBAAEMy0Fm4dwNl4xSwRM1mvX_9Pxb34dwEAACCAADijc4AAGB93daGX3cWjYE"
  - "CAACAgIAAxkBAAEMy0Jm4dwNuvyiJA1sYUCvfw5tWoMCdgACMgIAAuaV7QaLM2ZNyf628TYE"
  - "CAACAgIAAxkBAAEMy0Nm4dwNHRpbWt41kLlnEuMUJgEIKQACpBsAAqgKWUrUNlIK6zvyPDYE"
  - "CAACAgIAAxkBAAEMy0Rm4dwNGtQWzRq9NQXls14AAQnWbaEAAnNdAAIUsghLfmE_MOtxOZM2BA"
  - "CAACAgIAAxkBAAEMy0Vm4dwNxjptceK7TzZZfw3ARkZZ3gACKgADqXxOEULx1GcPEvI2NgQ"
  - "CAACAgIAAxkBAAEMy0Zm4dwNS98UwMPLR8Mqvbys1McUtgACTgADNyk8CORl0rNCudLbNgQ"
  - "CAACAgIAAxkBAAEMy0dm4dwNla6pDmM_dZ9j8YYwr6q96wACvwwAAtqgSUjbdUlgUyBd8DYE"
  - "CAACAgIAAxkBAAEMy0hm4dwNDQsDtb7i_JpfMomi0w07XAACsiYAAryI-UuJMZnCr_DiYzYE"
  - "CAACAgIAAxkBAAEMy0lm4dwNFMIT7faXougRiiSxsWSOtgACkSQAApF0aUhwTsMhNeo6xjYE"
  - "CAACAgIAAxkBAAEMy2Nm4dyz7LVG_8hTfJ67kwNSlTWkDgACBAADijc4AAFx0NNqDnJm4TYE"
  - "CAACAgIAAxkBAAEMy2Vm4dy3MwaAlqy6PvxMEaM7ETRM_AACLQADijc4AAGBowxjAqAlGzYE"
  - "CAACAgIAAxkBAAEMy2dm4dy6lNAkTXRnOz0lvGD0J_gMwQACEAADijc4AAESVXqKiwYE2zYE"
  - "CAACAgIAAxkBAAEMy2lm4dy8zlUTo0B8DQAB7RCpAzmDcfAAAhIAA4o3OAABdNBoq4aYn102BA"
  - "CAACAgIAAxkBAAEMy2tm4dzBiEMyfSySk0Yz1alJkAnA6QACFAADijc4AAGtl5dISqHmiDYE"
  - "CAACAgIAAxkBAAEMy21m4dzIhzMt40UoBmQN2_nl4DU5RQACHQADijc4AAEw0RBgpCTPAAE2BA"
  - "CAACAgIAAxkBAAEN0KxnszRWYnQGKuITb5uhW00yq_u7DAACbzIAAnpYaUlN0SYlfsk_PDYE"
daily_chickens_sticker_ids:
  - "CAACAgIAAxkBAAEMTMpmantz_jdQCBVWX7lGvMFzY3yJ2gACMgADWQxTEhiWxOGOtE5QNQQ"
  - "CAACAgIAAxkBAAEMTMxmant7DMxWMkuJlukfW18he0bWxwACxxIAAvx1yUuVMRcMrNODDzUE"
  - "CAACAgIAAxkBAAEMTM5manuKl9lgOtH4liLjJVwS9mShGAACbT4AAryw4Ej5B_iT5iPh-jUE"
  - "CAACAgIAAxkBAAEMTNBmanuS_8JnswE5SvXFNt-VLcJsLQACMToAAmoBEUg-bDbJH06o1jUE"
  - "CAACAgIAAxkBAAEMTNJmanuc6iTT_Yl4-8TRRwcQZEr4KgACFxYAApiMIUqmIBkkbPJysTUE"
  - "CAACAgEAAxkBAAEMTOBmapvVsK0DFbqBvHwUrfXWTokrYQACKQMAAsVP4EbOiBk_jpk-BzUE"
  - "CAACAgIAAxkBAAEMTOpmapxklEGyu66gmaPDmCLdyY8D9QACChYAAkipqUuWfRES_-NFMjUE"
  - "CAACAgIAAxkBAAEMTPBmapyacjjNLqzeo2HEBZGicpBrhwACAgADODo9EQYD6r0KZsLbNQQ"
  - "CAACAgIAAxkBAAENzypnsjAax9s5-GzGslVqT_zvvs1qtgACUgADnj-VA1nv3h_eNIpsNgQ"
  - "CAACAgIAAxkBAAENzyxnsjAkw2ytMDAF8493tiAeQ9b4MQACV-cBAAFji0YMnjDWWanMptQ2BA"
  - "CAACAgIAAxkBAAENzy5nsjA5Y1DFHUJ494v4GH7qhf7zvgACuR8AAjvTSEqk7CN6Yu2FEDYE"
  - "CAACAgIAAxkBAAENzzBnsjA_dzH1nanPVK57ft-u4VI7uQAC_gcAAlwCZQM8XWpCgEnu8jYE"
  - "CAACAgIAAxkBAAENzzJnsjBJo6wdenLEBoqfDZTKtRDdiwACtjgAAsAm-UtusC5-fIWoXTYE"
  - "CAACAgQAAxkBAAENzzRnsjBRsg34x-qkB9dl8wLl1lcI_AAC6QsAAlu7GFBrMruGqc9XujYE"
  - "CAACAgIAAxkBAAENzzZnsjBplbz3eALVaX8ns1WUY5lzogAC3CoAAuCjggdtpGI_-iOQkDYE"
  - "CAACAgIAAxkBAAENzzhnsjB1sv2iJJ9TcTA-AlBzRVlzfgACARMAAooQEEoc9G8sWBqQ4jYE"
  - "CAACAgIAAxkBAAENzzpnsjCL47G65S3r1Q-GMHBExfKmcQACTgADnj-VA1sKiIDrvwbaNgQ"
  - "CAACAgIAAxkBAAENzzxnsjCPZ8_eTT0BwLNgYqTsTsGDaQACaAADnj-VA8-uFk8EdIWZNgQ"
dp_sticker_id: "CAACAgIAAxkBAAELsFhl8hGciGxpkKi4-jhou97SOqwkvwACpT0AAkV6sEpqc1XNPnvOIDQE"
mocks:
  - username: "byegor"
    period: "72h"
    sticker_ids:
      - "CAACAgIAAxkBAAELtUJl9FKjhIGnyaUwO_IXh_SepPBgSAACzzwAAiTYUEn0kbWw7nXa1zQE"
  - username: "ollkostin"
    period: "72h"
    sticker_ids:
      - "CAACAgQAAxkBAAELvRpl-EweMqCeuggLoAo3ysvFmONONgACvRAAAqbxcR5BuzVAQyP23DQE"
  - username: "lk4d4"
    period: "72h"
    sticker_ids:
      - "CAACAgQAAxkBAAELu8Rl90uOqEMPwdCvcFIm8nBMpVNyoAACBwIAAnBt9gd0v3XadwsPfzQE"
  - username: "yukhyan"
    period: "24h"
    sticker_ids:
      - "CAACAgIAAxkBAAELvu5l-WzyKAuVR_3-pN9OdwTbagyrlwACFB0AAp5nqUiXjlLZ3jpJ2jQE"
      - "CAACAgIAAxkBAAELwmll_BDVE3wVFL6g8bDSd2EDPuXCBgACzhMAAkFImEhIWZNDtbMOAAE0BA"
      - "CAACAgIAAxkBAAELwmtl_BDaSFwk3r60go2hFLaKPhmzBAACFRgAAihmmEjcTuRs6Dq3HzQE"
      - "CAACAgIAAxkBAAELwm1l_BDecsQYMErbNHagr0j9fnXloQAC1BQAAvItmUhRwI4aaOsy5zQE"
      - "CAACAgIAAxkBAAELwm9l_BDw33MnhX3Mq0AJs0j7TqdMiwACjxkAAgznKEqMNBWL6wyaLjQE"
      - "CAACAgIAAxkBAAELwnFl_BEBRVEvPVbD3NgXoaQspYBmmwACYxYAAuxPmEi5ByG8q9K_xjQE"
      - "CAACAgUAAxkBAAEMB_NmMerYwbz4ODbApU8awHbBWCumugAC-QoAArgSIFb48XmSdN7rNDQE"
      - "CAACAgIAAxkBAAEMB_VmMerijbjCENY3kaRgiHE-LshhlwAC0R4AAj_ugEovh_CLELqXmjQE"
      - "CAACAgIAAxkBAAEMB_dmMerpS84bH3HXofwIqGllmUo57AACbRoAAu57mUhsViRGOLqifjQE"
  - username: "quazeeee"
    period: "48h"
    sticker_ids:
      - "CAACAgIAAxkBAAELwGNl-qw2RTN5nAeBv3aIoXdXUgXBywACcjUAAkbqsUsFx3HeYBqyNjQE"
  - username: "romangoward"
    period: "48h"
    sticker_ids: 
      - "CAACAgEAAxkBAAEM4mBm9b3oi05lz2KXbyG35vbZnbqJsQACCAADkzooTd0mr2l96bDKNgQ"
      - "CAACAgIAAxkBAAEM4mJm9b4J1P3GcSmJNgoz7LDfy_0ULQACexoAAqr0AUsWxy9aRgffRzYE"
greetings_new_users_templates:
  - "%s кто тебе рассказал про чат?"
  - "%s сколько пунктов в resumeworded?"
  - "%s как дела с ДП?"
  - "%s кто твой любимый смешарик?"
  - "%s дашь реф?"
  - "%s любишь лук с творогом?"
  - "%s сколько присед?"
  - "%s облизываешься на нидерландские зарплаты?"
  - "%s какой у тебя IQ?"
greetings_old_users_templates:
  - "%s однажды упав, в рай не возвращаются"
  - "%s снимай штаны"
  - "%s мы по тебе скучали, а ты по нам?"
  - "%s ну как ты?"
oborona:
  period: "25h"
  template: "Мой ты %s %s %s %s"
  words:
    - - "солнечный"
      - "траурный"
      - "плюшевый"
      - "бешеный"
      - "памятный"
      - "трепетный"
      - "базовый"
      - "скошенный"
      - "преданный"
      - "ласковый"
      - "пойманный"
      - "радужный"
      - "огненный"
      - "радостный"
      - "тензорный"
      - "шёлковый"
      - "пепельный"
      - "ламповый"
      - "жареный"
      - "загнанный"

    - - "зайчик"
      - "Верник"
      - "глобус"
      - "ветер"
      - "щавель"
      - "пёсик"
      - "копчик"
      - "ландыш"
      - "стольник"
      - "мальчик"
      - "дольшик"
      - "Игорь"
      - "невод"
      - "егерь"
      - "пончик"
      - "лобстер"
      - "жемчуг"
      - "кольщик"
      - "йогурт"
      - "овод"

    - - "стеклянного"
      - "ванильного"
      - "резонного"
      - "широкого"
      - "дешёвого"
      - "горбатого"
      - "собачьего"
      - "исконного"
      - "волшебного"
      - "картонного"
      - "лохматого"
      - "арбузного"
      - "огромного"
      - "запойного"
      - "великого"
      - "бараньего"
      - "вандального"
      - "едрёного"
      - "парадного"
      - "укромного"

    - - "глаза"
      - "плова"
      - "Пельша"
      - "мира"
      - "деда"
      - "жира"
      - "мема"
      - "ада"
      - "бура"
      - "жала"
      - "нёба"
      - "гунна"
      - "хлама"
      - "шума"
      - "воза"
      - "сала"
      - "фена"
      - "зала"
      - "рака"
      - "Глеба"
