badger_path: "data/badger"
features:
  snippets_generation_enabled: false
tg:
  api_key: ""
  long_poller_timeout: "10s"
  admin_chat_id: 230400818
rod:
  host: "rod" # inside docker, for local use "docker run --rm -p 7317:7317 ghcr.io/go-rod/rod:v0.116.1" and 127.0.0.1 as host
  port: 7317
  downloads_folder: "/opt/drone/data/rod/downloads"
image_generator:
  carbon_url: "http://carbon:3000"
  rayso_url: "http://rayso:3001"
  javahighlight_url: "http://javahighlight:3002"
  use_carbon: false
  use_rayso: false
  use_javahighlight: true
  rod_downloads_folder: "/opt/drone/data/rod/downloads"
boardwhite:
  chat_id: -1001640461540
  leetcode_thread_id: 10095
  leetcode_chickens_thread_id: 372377
  greetings_thread_id: 11214
leetcode:
  session: ""
  csrf: ""
leetcode_daily:
  cron: "0 1 * * *" # every day at 01:00 UTC
  rating_cron: "0 6 1 * *" # every month at 06:00 UTC
neetcode_daily:
  cron: "0 12 * * *" #  every day at 12:00 UTC
  rating_cron: "1 6 1 * *" # every month at 06:01 UTC
daily_sticker_ids:
  - "CAACAgIAAxkBAAELpiFl7G4Rn8WQBK3AaDiAMn6ixTUR7gACzzkAAr-TAAFK91qMnVpp9TQ0BA"
  - "CAACAgIAAxkBAAELqk5l72yJkbx4_vskG3n6zWoWaAnA3QACazYAArJX2UsY5inoNwaFoTQE"
  - "CAACAgIAAxkBAAELsFZl8hFWX-2VvyppubPYPnLFrVeLPgACZjEAAmSSoUrAsMs8kC1omDQE"
  - "CAACAgIAAxkBAAELsFRl8hE8RstoYI8E3RfKk2N1LRX-qQAC4TUAAhJs2ElFZyKM69wJfDQE"
  - "CAACAgIAAxkBAAELsFJl8hEuJlU_1RK4nbpq3_iuZYsAATAAAi01AALtZihJuuf3iNlNcbU0BA"
  - "CAACAgIAAxkBAAELsFBl8hEnQ9Ie_ANBN_TfzbDjvMck2wACVToAAhqdoEiRsQbJLo-jijQE"
  - "CAACAgIAAxkBAAELsE5l8hEfhr-0Dn7BfsI9sDWA3I0t0wACSzUAAtS3aUj_OJb99K6DkjQE"
  - "CAACAgIAAxkBAAELsExl8hEZTP0DFsf6hUDiZnx-i9I25wACpTEAAlp3YUhJNRORPRx_5DQE"
  - "CAACAgIAAxkBAAELsEpl8hERg5mpamVfTo_SCgZRatbi6wACCzcAAqVsKEjLAvd1EuqdLzQE"
  - "CAACAgIAAxkBAAELsEhl8hENAzygO8iFauBYZD0XPYqD3gACkTQAArnoCUjvaNgUd-BoHDQE"
  - "CAACAgIAAxkBAAELsEZl8hD-i6wYaeLUMtP8MWhZwZoy3gACAjMAAs0gAUjsT0apWa4cRTQE"
  - "CAACAgIAAxkBAAELsERl8hD1xsuLUYRD9F4a8ekVAgg8VAACgDgAAsuH-UvwActGs5DfMzQE"
  - "CAACAgIAAxkBAAELsEJl8hDUc-b0jyDfeH6Ct2McMp4mlAACOzcAAquEmUsMP7ObsCcumTQE"
  - "CAACAgIAAxkBAAEMTOJmapw65q2fQiOQ-q3_B6RV9_7qagACNAADBcpWCO24fpev5IapNQQ"
  - "CAACAgIAAxkBAAEMTORmapw_xM94EVu2j6zINAlSYbcsogACTAADBcpWCJEC-PYX7CmtNQQ"
  - "CAACAgIAAxkBAAEMTOZmapxMTnRwYwmwsUaEsDw70HbfJwACEAADBcpWCOqNywPZHSK1NQQ"
  - "CAACAgIAAxkBAAEMTOhmapxcGWbkHGnKsEj_XLSOC8FtJgACwRYAAmLD-EldkLhdqjpVMDUE"
  - "CAACAgIAAxkBAAEMTOxmapxstQLBnvTk3zzEHJ-cHLiBdgACkh4AAqhMIUh2wIwKN77UfzUE"
  - "CAACAgIAAxkBAAEMTO5mapx14v9sDaCBqbMbjOCuaTmj-wACAx4AAlOqQErr0hfP2b25hzUE"
  - "CAACAgEAAxkBAAEMTPJmapyrwuh-bHr1DANmoRaiD7_XwQAC7xIAApl_iAJsyiP2eI4MKDUE"
  - "CAACAgEAAxkBAAEMTPRmapy22Zjj6OV0aAwVJoLgpo3YTAACoQ8AApl_iAIczmqdOf8MDTUE"
  - "CAACAgEAAxkBAAEMTPZmapy8EMeLka9fZlAHOJqcPcYB8gACow8AApl_iALey-njdminmjUE"
  - "CAACAgIAAxkBAAEMTPhmapzuIaxJjpwwvHJAtAL4a_0Q6gACUgoAAtA90gixaS0UHuYwgjUE"
  - "CAACAgIAAxkBAAEMTPpmap46qgL2bAOFrTCmm_qlNevK8gACMk0AAjtToEqXoqlSuH4pwTUE"
  - "CAACAgIAAxkBAAEMTPxmaqA3xQs2VIIsvRe_Zz8b8f_YfgACDgADWQxTEp_ypEYr7NfVNQQ"
  - "CAACAgIAAxkBAAEMTP5maqA87gNxFLfOIVnVKQb9p87FwAACAQADWQxTEoGwOR2Ph1igNQQ"
  - "CAACAgIAAxkBAAEMTQABZmqgV7BhQEcw5KIbsNts8sHOJgYAAikAA1kMUxKOy898mJBVazUE"
  - "CAACAgIAAxkBAAEMTQJmaqB9_d9Ciu3HY3KXTrTa-QljMwACLgADWQxTEhJbEPYsQmF0NQQ"
daily_chickens_sticker_ids:
  - "CAACAgIAAxkBAAEMTMpmantz_jdQCBVWX7lGvMFzY3yJ2gACMgADWQxTEhiWxOGOtE5QNQQ"
  - "CAACAgIAAxkBAAEMTMxmant7DMxWMkuJlukfW18he0bWxwACxxIAAvx1yUuVMRcMrNODDzUE"
  - "CAACAgIAAxkBAAEMTM5manuKl9lgOtH4liLjJVwS9mShGAACbT4AAryw4Ej5B_iT5iPh-jUE"
  - "CAACAgIAAxkBAAEMTNBmanuS_8JnswE5SvXFNt-VLcJsLQACMToAAmoBEUg-bDbJH06o1jUE"
  - "CAACAgIAAxkBAAEMTNJmanuc6iTT_Yl4-8TRRwcQZEr4KgACFxYAApiMIUqmIBkkbPJysTUE"
  - "CAACAgEAAxkBAAEMTOBmapvVsK0DFbqBvHwUrfXWTokrYQACKQMAAsVP4EbOiBk_jpk-BzUE"
  - "CAACAgIAAxkBAAEMTOpmapxklEGyu66gmaPDmCLdyY8D9QACChYAAkipqUuWfRES_-NFMjUE"
  - "CAACAgIAAxkBAAEMTPBmapyacjjNLqzeo2HEBZGicpBrhwACAgADODo9EQYD6r0KZsLbNQQ"
dp_sticker_id: "CAACAgIAAxkBAAELsFhl8hGciGxpkKi4-jhou97SOqwkvwACpT0AAkV6sEpqc1XNPnvOIDQE"
mocks:
  - username: "byegor"
    period: "72h"
    sticker_ids:
      - "CAACAgIAAxkBAAELtUJl9FKjhIGnyaUwO_IXh_SepPBgSAACzzwAAiTYUEn0kbWw7nXa1zQE"
  - username: "ollkostin"
    period: "72h"
    sticker_ids:
      - "CAACAgQAAxkBAAELvRpl-EweMqCeuggLoAo3ysvFmONONgACvRAAAqbxcR5BuzVAQyP23DQE"
  - username: "lk4d4"
    period: "72h"
    sticker_ids:
      - "CAACAgQAAxkBAAELu8Rl90uOqEMPwdCvcFIm8nBMpVNyoAACBwIAAnBt9gd0v3XadwsPfzQE"
  - username: "yukhyan"
    period: "24h"
    sticker_ids:
      - "CAACAgIAAxkBAAELvu5l-WzyKAuVR_3-pN9OdwTbagyrlwACFB0AAp5nqUiXjlLZ3jpJ2jQE"
      - "CAACAgIAAxkBAAELwmll_BDVE3wVFL6g8bDSd2EDPuXCBgACzhMAAkFImEhIWZNDtbMOAAE0BA"
      - "CAACAgIAAxkBAAELwmtl_BDaSFwk3r60go2hFLaKPhmzBAACFRgAAihmmEjcTuRs6Dq3HzQE"
      - "CAACAgIAAxkBAAELwm1l_BDecsQYMErbNHagr0j9fnXloQAC1BQAAvItmUhRwI4aaOsy5zQE"
      - "CAACAgIAAxkBAAELwm9l_BDw33MnhX3Mq0AJs0j7TqdMiwACjxkAAgznKEqMNBWL6wyaLjQE"
      - "CAACAgIAAxkBAAELwnFl_BEBRVEvPVbD3NgXoaQspYBmmwACYxYAAuxPmEi5ByG8q9K_xjQE"
      - "CAACAgUAAxkBAAEMB_NmMerYwbz4ODbApU8awHbBWCumugAC-QoAArgSIFb48XmSdN7rNDQE"
      - "CAACAgIAAxkBAAEMB_VmMerijbjCENY3kaRgiHE-LshhlwAC0R4AAj_ugEovh_CLELqXmjQE"
      - "CAACAgIAAxkBAAEMB_dmMerpS84bH3HXofwIqGllmUo57AACbRoAAu57mUhsViRGOLqifjQE"
  - username: "quazeeee"
    period: "48h"
    sticker_ids:
      - "CAACAgIAAxkBAAELwGNl-qw2RTN5nAeBv3aIoXdXUgXBywACcjUAAkbqsUsFx3HeYBqyNjQE"
greetings:
  - "%s кто тебе рассказал про чат?"
  - "%s сколько пунктов в resumeworded?"
  - "%s как дела с ДП?"
  - "%s кто твой любимый смешарик?"
  - "%s дашь реф?"
  - "%s любишь лук с творогом?"
  - "%s сколько присед?"
  - "%s облизываешься на нидерландские зарплаты?"
  - "%s какой у тебя IQ?"
