package leetcode

import (
	_ "embed"
	"encoding/json"
	"fmt"
)

// auto-generated by command
// python ./cmd/python/lc-load-questions/main.py > neetcode/questions.json
//
//go:embed questions.json
var rawQuestions []byte

type Question struct {
	ID         string     `json:"id"`
	IsPremium  bool       `json:"is_premium"`
	Link       string     `json:"link"`
	Name       string     `json:"name"`
	Acceptance float32    `json:"acceptance"`
	Difficulty Difficulty `json:"difficulty"`
}

func Questions() ([]Question, error) {
	var questions []Question
	if err := json.Unmarshal(rawQuestions, &questions); err != nil {
		return nil, fmt.Errorf("parse rawQuestions: %w", err)
	}

	return questions, nil
}
