name: Go

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.21'
    - name: gotidy
      run: |
        go mod verify
        go mod tidy
        git diff --exit-code || ( echo "go mod tidy changed something" && git status && exit 1)
    - name: golangci-lint
      uses: golangci/golangci-lint-action@v4
      with:
        version: v1.54
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.21'
    - name: Test
      run: go test -skip='TestSkip.*' -race -v ./...
